### ISSUE TITLE
v0.2.0 Upload hangs

### ISSUE THREAD

**Issue by markymif** [rullzer/dropit#19] opened 2019-03-05 11:48 UTC
Next Cloud 15.0.2
Uploaded Text file just fine, unloaded 8mb file, fine.
Uploaded 33mb file and it hung half way.  I received the email notifications for all but the FTP view shows the file as 0 bytes
![image](https://user-images.githubusercontent.com/17123047/53803364-6f55ea80-3f3c-11e9-873d-012babd7757a.png)
![image](https://user-images.githubusercontent.com/17123047/53803383-7c72d980-3f3c-11e9-8257-071dae2b5450.png)
FTP
![image](https://user-images.githubusercontent.com/17123047/53803401-898fc880-3f3c-11e9-9a8e-594313ef42df.png)

I have had this issue with all versions of Dropit and Nextcloud

**Comment by nickvergessen** [comment] 2019-04-01 12:06
Duplicate of #13

**Closed by nickvergessen** 2019-04-01 12:06 UTC
